### ISSUE TITLE
There seems to be a mixup with the sources for ST drops

### ISSUE THREAD

**Issue by Cabro** [snowflame0/AtlasLootClassic_Cata#124]
**Describe the bug**
![image](https://github.com/user-attachments/assets/ac01ceaf-35a9-485f-bdff-c976beac8936)
Item tooltips for sources don't match what AtlasLoot shows in the loot tables.
Looks like all drops are offset to the old loot tables, maybe this is the reason this is showing like this?

**Comment by snowflame0** [comment]
Yep, exactly as you said.

This issue is known, gonna need to update all the old world dungeons and re-generate all the source data. Workin' on it. I can maybe just fix this one manually for now

**Comment by snowflame0** [comment]
Ok, should be fixed on next release. I also removed the drop rate data, because it's meaningless now. The tables have been mixed/changed, so who knows.

Feel free to open more issues if you notice any more issues with old world stuff, definitely needs a revamp. Lots of outdated/removed content in there.
