### ISSUE TITLE
Random items wrongfully added.

### ISSUE THREAD

**Issue by Cabro** [snowflame0/AtlasLootClassic_Cata#59]
Hoping you guys will do a better job than the original devs.
There are maaaany low level items that are wrongfully added to the loottables, as if they drop from raid bosses or achievements. Would you please go though these and remove them?
![image](https://github.com/snowflame0/AtlasLootClassic_Cata/assets/1155017/d5ebbba9-5e37-4aaf-89a1-ab2cfc28ca86)
![image](https://github.com/snowflame0/AtlasLootClassic_Cata/assets/1155017/28d98310-8b2b-4764-9377-d6f97ebdc9ff)
And the list goes on, there are way more than those 2 example items i showed.
/pray

**Comment by gitenarra** [comment]
looks like issues with IDs (item ID number same as achievements or spells), not sure if this can be fixed (or if it will be easy)

**Comment by snowflame0** [comment]
There are 12,000+ items to go through, so we will have to script it somehow.

I do see that at some point the Wrath sources added achievement IDs as if they were items to the sources list, causing issues like screenshot #2. So, I will figure out what IDs belong to achievements and just remove all of those, as they shouldn't be there. Probably just a bug with the script that they used to parse the lists of items.

The issue with screenshot #1 seems to be because SFK, Deadmines, and several other dungeons were changed and we have temporarily removed them from the Classic dungeons and raids table, but haven't updated the sources list. I'll find a way to fix it, maybe need to remake the old tables.

**Comment by snowflame0** [comment]
Feel free to add as many screenshots as you find of mistagged items, showing the item ID preferably. It might help figure out all those edge cases.

**Comment by snowflame0** [comment]
Ok, should be fixed on next beta. Please open a new issue if you find any more that are incorrect.
